name: Test CI

on:
  push:
    branches-ignore:
      - master

  pull_request:

env:
  PLATFORM: linux/amd64
  DOCKER_REPO: renovate/ubuntu
  DOCKER_CACHE: ubuntu

jobs:
  build:
    runs-on: ubuntu-latest

    timeout-minutes: 20

    steps:
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: v0.3.1

      - uses: actions/checkout@v2

      - name: docker cache
        id: docker-cache
        uses: actions/cache@v1
        with:
          path: .cache
          key: ${{ runner.os }}-docker-${{ hashFiles('Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build
        uses: renovatebot/gh-action@v0
        with:
          command: "build"

      - name: Build the Docker image
        run: |
          cache_from=$([ -d .cache ] && echo -n '--cache-from=type=local,src=.cache' || echo -n '')
          docker buildx build \
            --load \
            --tag ${DOCKER_REPO} --tag ${DOCKER_REPO}:18.04 \
            --cache-to=type=local,dest=.cache,mode=max \
            --cache-from=renovate/docker-build-cache:${DOCKER_CACHE} \
            $cache_from \
            .

      - name: Test the Docker images
        run: docker run --rm -t ${DOCKER_REPO} git --version

      - name: Image history latest
        run: docker history ${DOCKER_REPO}

      - name: Images size
        run: docker image ls | grep ${DOCKER_REPO}
